name: Build
on:
  - push
  - pull_request
jobs:
  build-windows:
    name: Build Windows
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        qt: [5.15.2]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1  # not v2! TODO: why though?
        with:
          path: ../Qt
          key: ${{ matrix.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt }}
          arch: win64_mingw81
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Install ZLib
        run: |
          Invoke-WebRequest -Uri "https://sourceforge.net/projects/gnuwin32/files/zlib/1.2.3/zlib-1.2.3.exe" -OutFile "zlib-1.2.3.exe"
          .\\zlib-1.2.3.exe /VERYSILENT NORESTART

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.22.x'

      - name: Build
        run: |
          mkdir -f build
          mkdir -f install
          cmake -B build -S . -DCMAKE_INSTALL_PREFIX=install
          make -C build -j2 install # nproc on Windows???

      - uses: actions/upload-artifact@v2
        with:
          name: portable-binary.${{ github.sha }}.${{ matrix.os }}-${{ runner.arch }}
          path: install/**
